"""Static problem pages and a bilingual browser-search index.

The web UI deliberately receives no credibility or review metadata.  Those
fields belong on the generated, reviewable Markdown problem pages; the search
surface ranks every engineering problem only by textual relevance.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re
import unicodedata
from typing import Any, Dict, Iterable, List, Mapping, Sequence, Tuple
from urllib.parse import quote, urlparse

from .language import BILINGUAL_TECHNICAL_GLOSSARY, infer_bilingual_terms
from .models import ClaimStatus, EngineeringClaim, SourceRecord


DEFAULT_REPOSITORY_URL = "https://github.com/GuangjunZeng/Humanoid-WBC-Handbook"
DEFAULT_BRANCH = "main"
GENERATED_MARKER = "<!-- Generated by wbc-handbook render-problems; do not edit. -->"
ANSWER_STATUSES = {"resolved", "partial", "unresolved", "conflicting"}
FORBIDDEN_SEARCH_FIELDS = {
    "answer_status",
    "confidence",
    "credibility",
    "review_status",
    "status",
    "verification_status",
}
HOMEPAGE_REVIEW_LANGUAGE = re.compile(
    r"\b(?:resolved|partial|unresolved|conflicting)\b|"
    r"可信度|置信度|证据状态|问题状态|待独立核验|待核验|未解决|存在冲突",
    re.IGNORECASE,
)


# A deliberately small symptom vocabulary complements the canonical bilingual
# robotics glossary.  It improves recall without pretending to translate free
# prose or introducing an opaque model into the search path.
SEARCH_ALIAS_GROUPS: Sequence[Tuple[str, ...]] = (
    ("真机", "实机", "hardware", "real robot", "physical robot"),
    ("仿真", "模拟器", "simulation", "simulator"),
    ("乱动", "抖动", "振荡", "不稳定", "发散", "unstable", "oscillation", "divergence", "random motion"),
    ("站不住", "无法站立", "跌倒", "cannot stand", "unstable standing", "falling"),
    ("打滑", "滑移", "slip", "slipping"),
    ("不可行", "无解", "求解失败", "infeasible", "infeasibility", "solver failure"),
    ("状态估计漂移", "估计漂移", "ekf drift", "state estimation drift", "estimator drift"),
    ("观测缩放", "观测尺度", "observation scale", "observation scaling"),
    ("动作缩放", "动作尺度", "action scale", "action scaling"),
    ("延迟", "时延", "latency", "delay"),
    ("关节顺序", "关节映射", "joint order", "joint mapping", "dof mapping"),
    ("坐标系", "坐标变换", "frame convention", "coordinate frame", "frame transform"),
    ("力矩", "扭矩", "torque", "joint torque"),
    ("接触", "触地", "contact", "ground contact"),
)


class WebSearchError(ValueError):
    """Raised when web-search artifacts cannot be generated safely."""


@dataclass(frozen=True)
class WebProblem:
    problem_id: str
    title: str
    summary: str
    keywords: Tuple[str, ...]
    aliases: Tuple[str, ...]
    search_text: str
    relative_path: str
    url: str
    markdown: str

    def search_item(self) -> Dict[str, Any]:
        return {
            "id": self.problem_id,
            "title": self.title,
            "summary": self.summary,
            "keywords": list(self.keywords),
            "aliases": list(self.aliases),
            "search_text": self.search_text,
            "url": self.url,
        }


def normalize_search_text(value: Any) -> str:
    """Return a stable lowercase NFKC representation for indexing."""

    folded = unicodedata.normalize("NFKC", str(value)).casefold()
    folded = re.sub(r"[^0-9a-z\u3400-\u4dbf\u4e00-\u9fff.+_-]+", " ", folded)
    return " ".join(folded.split())


def _stable_strings(values: Iterable[Any]) -> Tuple[str, ...]:
    result: List[str] = []
    seen = set()
    for value in values:
        text = str(value).strip()
        if not text:
            continue
        key = normalize_search_text(text)
        if not key or key in seen:
            continue
        seen.add(key)
        result.append(text)
    return tuple(result)


def _cjk_bigrams(value: str) -> Tuple[str, ...]:
    grams: List[str] = []
    for run in re.findall(r"[\u3400-\u4dbf\u4e00-\u9fff]+", value):
        if len(run) == 1:
            grams.append(run)
        else:
            grams.extend(run[index:index + 2] for index in range(len(run) - 1))
    return _stable_strings(grams)


def _homepage_summary(value: Any) -> str:
    """Keep review labels on detail pages, not on the fast-search surface."""

    text = " ".join(str(value).split())
    sentences = re.split(r"(?<=[。！？.!?])\s*", text)
    kept = [
        sentence for sentence in sentences
        if sentence and not HOMEPAGE_REVIEW_LANGUAGE.search(sentence)
    ]
    if kept:
        return " ".join(kept)
    return HOMEPAGE_REVIEW_LANGUAGE.sub("", text).strip(" ；;，,。.")


def _term_aliases(terms: Iterable[Any]) -> Tuple[str, ...]:
    aliases: List[str] = []
    for value in terms:
        term = str(value).strip()
        if not term:
            continue
        aliases.append(term)
        match = re.match(r"^(.*?)\s*[（(](.*?)[）)]$", term)
        if match:
            aliases.append(match.group(1).strip())
            aliases.append(match.group(2).strip())
            aliases.extend(part.strip() for part in match.group(2).split(","))
    return _stable_strings(aliases)


def _expanded_aliases(text: str, bilingual_terms: Iterable[Any]) -> Tuple[str, ...]:
    aliases = list(_term_aliases(bilingual_terms))
    normalized = normalize_search_text(" ".join([text, *aliases]))
    for group in SEARCH_ALIAS_GROUPS:
        if any(normalize_search_text(alias) in normalized for alias in group):
            aliases.extend(group)
    if (
        any(term in normalized for term in ("状态估计", "state estimation", "ekf"))
        and any(term in normalized for term in ("漂移", "drift"))
    ):
        aliases.extend((
            "状态估计漂移", "估计器漂移", "EKF drift",
            "state estimation drift", "estimator drift",
        ))
    if (
        any(term in normalized for term in ("足端", "足底", "支撑足", "foot", "feet"))
        and any(term in normalized for term in ("打滑", "滑移", "slip", "slipping"))
    ):
        aliases.extend((
            "足端打滑", "足底打滑", "支撑足滑移",
            "foot slip", "slipping foot", "contact slip",
        ))
    for canonical, glossary_aliases in BILINGUAL_TECHNICAL_GLOSSARY:
        candidates = (canonical, *glossary_aliases)
        if any(normalize_search_text(alias) in normalized for alias in candidates):
            aliases.extend(candidates)
    return _stable_strings(aliases)


def _search_blob(*values: Any) -> str:
    normalized = normalize_search_text(" ".join(str(value) for value in values if value))
    normalized = " ".join(HOMEPAGE_REVIEW_LANGUAGE.sub(" ", normalized).split())
    grams = _cjk_bigrams(normalized)
    return " ".join([normalized, *grams]).strip()


def _qa_problem_id(source_id: str, question: str) -> str:
    digest = hashlib.sha256(
        normalize_search_text(question).encode("utf-8")
    ).hexdigest()[:12]
    return f"{source_id}.{digest}"


def _github_url(repository_url: str, branch: str, relative_path: str) -> str:
    repository_url = repository_url.rstrip("/")
    parsed = urlparse(repository_url)
    if parsed.scheme != "https" or parsed.netloc != "github.com":
        raise WebSearchError("repository_url must be an https://github.com URL")
    safe_branch = quote(branch, safe="._-")
    safe_path = quote(relative_path, safe="/._-")
    return f"{repository_url}/blob/{safe_branch}/{safe_path}"


def _md_inline(value: Any) -> str:
    return " ".join(str(value).replace("\r", " ").replace("\n", " ").split())


def _md_list(values: Iterable[Any]) -> List[str]:
    return [f"- {_md_inline(value)}" for value in values if str(value).strip()]


def _section(
    lines: List[str], title: str, values: Iterable[Any], empty_note: str = ""
) -> None:
    rendered = _md_list(values)
    if not rendered:
        if empty_note:
            lines.extend(["", f"## {title}", "", f"- {_md_inline(empty_note)}"])
        return
    lines.extend(["", f"## {title}", "", *rendered])


def _claim_grade(claim: EngineeringClaim) -> Tuple[str, str]:
    if claim.status == ClaimStatus.REVIEWED:
        return "L3 已审核工程结论", "该结论已经通过 Handbook 的 EngineeringClaim 审核门槛。"
    return "L1 草稿或部分经验", "该结论仍处于草稿状态，尚未完成 Handbook 审核。"


def _qa_grade(status: str) -> Tuple[str, str]:
    if status == "resolved":
        return "L2 来源报告已解决，待独立核验", "原来源报告问题已解决，但尚不等于跨机器人、跨版本通用结论。"
    if status == "partial":
        return "L1 草稿或部分经验", "当前只有部分处理经验或排查线索。"
    return "L0 未解决或存在冲突", "当前讨论未解决，或不同来源之间仍存在冲突。"


def _claim_problem(
    claim: EngineeringClaim,
    sources_by_id: Mapping[str, SourceRecord],
    repository_url: str,
    branch: str,
) -> WebProblem:
    relative_path = f"content/problems/{claim.claim_id}.md"
    grade, grade_note = _claim_grade(claim)
    applicability = claim.applicability
    context_text = " ".join([
        claim.question,
        claim.statement,
        *claim.tags,
        *applicability.robots,
        *applicability.simulators,
        *applicability.controllers,
        *applicability.environments,
        *applicability.assumptions,
    ])
    bilingual_terms = infer_bilingual_terms(context_text, limit=12)
    keywords = _stable_strings([
        *claim.tags,
        claim.domain.value,
        *applicability.robots,
        *applicability.simulators,
        *applicability.controllers,
        *applicability.environments,
        *bilingual_terms,
    ])
    aliases = _expanded_aliases(context_text, bilingual_terms)

    lines = [
        GENERATED_MARKER,
        "",
        f"# {_md_inline(claim.question)}",
        "",
        f"> **当前答案：** {_md_inline(claim.statement)}",
        "",
        "## 可信度与审核状态",
        "",
        f"- **手册分级：** `{grade}`",
        f"- **分级说明：** {_md_inline(grade_note)}",
        f"- **置信度：** `{claim.confidence:.2f}`",
        f"- **置信度理由：** {_md_inline(claim.confidence_rationale)}",
        f"- **安全等级：** `{claim.safety_level.value}`",
        f"- **复核日期：** `{claim.review_due_at}`",
    ]
    _section(lines, "关键术语", bilingual_terms)
    _section(lines, "适用机器人", applicability.robots)
    _section(lines, "适用模拟器", applicability.simulators)
    _section(lines, "控制器与方法", applicability.controllers)
    _section(lines, "适用环境", applicability.environments)
    _section(lines, "成立假设", applicability.assumptions)

    lines.extend([
        "",
        "## 排查与验证",
        "",
        "- 先核对适用机器人、模拟器、控制器、环境和成立假设，再沿下方证据定位复核原始实验或实现。",
        "",
        "## 结果",
        "",
        f"- {_md_inline(claim.statement)}",
    ])
    _section(
        lines,
        "限制",
        applicability.assumptions,
        empty_note="当前 Claim 未记录额外成立假设；仍不得超出证据所覆盖的机器人、版本和环境。",
    )

    if claim.safety_case is not None:
        safety = claim.safety_case
        lines.extend([
            "",
            "## 安全提示",
            "",
            f"- **仿真验证：** {'是' if safety.simulation_validated else '否'}",
            f"- **指令限制：** {_md_inline(safety.command_limits)}",
            f"- **急停：** {_md_inline(safety.emergency_stop)}",
            f"- **保护措施：** {_md_inline(safety.protective_controls)}",
            f"- **机器人特定警告：** {_md_inline(safety.robot_specific_warning)}",
            f"- **分阶段部署：** {_md_inline(safety.staged_deployment)}",
        ])
    else:
        lines.extend([
            "",
            "## 安全提示",
            "",
            "- 本页是证据导航，不是可直接执行的实机控制指令；涉及硬件时仍需仿真验证、限幅、保护装置和人工审核。",
        ])

    lines.extend(["", "## 证据", ""])
    for link in claim.evidence:
        source = sources_by_id.get(link.source_id)
        if source is None:
            raise WebSearchError(
                f"claim {claim.claim_id} references missing source {link.source_id}"
            )
        note = f"；{_md_inline(link.note)}" if link.note else ""
        lines.append(
            f"- [{_md_inline(source.title)}](<{source.canonical_url}>) — "
            f"`{link.role.value}/{link.strength.value}`；{_md_inline(link.locator)}{note}"
        )
    lines.extend([
        "",
        "> 本页提供工程证据导航，不替代机器人厂商限制、现场风险评估和实机授权。",
        "",
    ])
    markdown = "\n".join(lines)
    url = _github_url(repository_url, branch, relative_path)
    search_text = _search_blob(
        claim.question, claim.statement, " ".join(keywords), " ".join(aliases)
    )
    return WebProblem(
        problem_id=claim.claim_id,
        title=claim.question,
        summary=_homepage_summary(claim.statement),
        keywords=keywords,
        aliases=aliases,
        search_text=search_text,
        relative_path=relative_path,
        url=url,
        markdown=markdown,
    )


def _mapping_strings(value: Any) -> List[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _qa_problem(
    source: SourceRecord,
    qa: Mapping[str, Any],
    repository_url: str,
    branch: str,
) -> WebProblem:
    question = str(qa.get("question_zh", "")).strip()
    answer = str(qa.get("answer_zh", "")).strip()
    status = str(qa.get("answer_status", "")).strip()
    if not question or not answer or status not in ANSWER_STATUSES:
        raise WebSearchError(
            f"{source.source_id} has an invalid engineering_qa card"
        )
    problem_id = _qa_problem_id(source.source_id, question)
    relative_path = f"content/problems/{problem_id}.md"
    metadata = source.metadata
    details = metadata.get("engineering_details", {})
    if not isinstance(details, Mapping):
        details = {}
    bilingual_terms = _mapping_strings(qa.get("bilingual_terms"))
    if not bilingual_terms:
        bilingual_terms = infer_bilingual_terms(
            f"{question} {answer} {source.summary}", limit=12
        )
    keywords = _stable_strings([
        *_mapping_strings(metadata.get("components")),
        *_mapping_strings(metadata.get("robot_platforms")),
        *_mapping_strings(metadata.get("domain_hints")),
        metadata.get("scope_id", ""),
        metadata.get("platform", ""),
        *bilingual_terms,
    ])
    discovery_queries = _stable_strings([
        metadata.get("query", ""),
        *_mapping_strings(metadata.get("queries")),
    ])
    context_text = " ".join([
        question,
        answer,
        source.title,
        source.summary,
        *keywords,
        *discovery_queries,
        *[item for values in details.values() if isinstance(values, list) for item in values],
    ])
    aliases = _expanded_aliases(context_text, bilingual_terms)
    grade, grade_note = _qa_grade(status)
    credibility = qa.get("credibility")

    lines = [
        GENERATED_MARKER,
        "",
        f"# {_md_inline(question)}",
        "",
        f"> **当前答案：** {_md_inline(answer)}",
        "",
        "## 可信度与证据状态",
        "",
        f"- **手册分级：** `{grade}`",
        f"- **分级说明：** {_md_inline(grade_note)}",
        f"- **问题状态：** `{status}`",
        f"- **证据状态：** `{_md_inline(qa.get('verification_status', 'candidate'))}`",
    ]
    if isinstance(credibility, Mapping):
        final_grade = credibility.get("final_grade") or credibility.get("computed_grade")
        rationale = credibility.get("rationale_zh")
        if final_grade:
            lines.append(f"- **来源内评级：** {_md_inline(final_grade)}")
        if rationale:
            lines.append(f"- **评级理由：** {_md_inline(rationale)}")

    completeness = metadata.get("collection_completeness")
    if isinstance(completeness, Mapping):
        lines.append(
            f"- **采集完整性：** `{_md_inline(completeness.get('status', 'partial_visible'))}`；"
            f"停止原因：{_md_inline(completeness.get('stop_reason', '未报告'))}"
        )

    _section(lines, "关键术语", bilingual_terms)
    section_map = (
        ("问题与症状", [*details.get("problem_statements", []), *details.get("symptoms", [])], "原始来源未单独列出更多症状；以本页问题文本为准。"),
        ("环境", details.get("environments", []), "原始来源未提供可复现的软硬件环境。"),
        ("优先排查", details.get("diagnostics", []), "原始来源未给出可复核的优先排查步骤。"),
        ("可能原因", details.get("suspected_causes", []), ""),
        ("处理过程", details.get("attempts", []), ""),
        ("有效处理", details.get("effective_fixes", []), ""),
        ("结果", details.get("outcomes", []), "原始来源未报告最终结果。"),
        ("限制", details.get("limits", []), "原始来源未说明适用限制；不得据此外推。"),
        ("安全提示", details.get("safety_notes", []), "原始来源未提供独立安全提示；涉及实机时必须先做仿真、限幅和保护验证。"),
        ("图片与图文证据", metadata.get("media_summaries", []), "原始来源未提供可核验图片，或当前采集未包含可分析的图文证据。"),
    )
    for section_title, values, empty_note in section_map:
        _section(
            lines,
            section_title,
            values if isinstance(values, list) else [],
            empty_note=empty_note,
        )
    applicability = qa.get("applicability")
    if applicability:
        _section(lines, "适用边界", [applicability])

    source_url = str(qa.get("source_url") or source.canonical_url).strip()
    locator = str(qa.get("source_locator", "原帖")).strip()
    lines.extend([
        "",
        "## 原始来源",
        "",
        f"- **来源定位：** {_md_inline(locator)}",
        f"- **问题或回复：** [{_md_inline(source.title)}](<{source_url}>)",
    ])
    if source_url != source.canonical_url:
        lines.append(
            f"- **根来源：** [{_md_inline(source.title)}](<{source.canonical_url}>)"
        )
    lines.extend([
        "",
        "> 社区和 Issue 经验用于缩短排查路径；未经论文、源码、官方文档或独立复现核验时，不应直接升级为跨平台工程结论。",
        "",
    ])
    markdown = "\n".join(lines)
    url = _github_url(repository_url, branch, relative_path)
    search_text = _search_blob(
        question, answer, source.title, source.summary,
        " ".join(keywords), " ".join(aliases), context_text,
    )
    return WebProblem(
        problem_id=problem_id,
        title=question,
        summary=_homepage_summary(answer),
        keywords=keywords,
        aliases=aliases,
        search_text=search_text,
        relative_path=relative_path,
        url=url,
        markdown=markdown,
    )


def collect_web_problems(
    sources: Iterable[SourceRecord],
    claims: Iterable[EngineeringClaim],
    repository_url: str = DEFAULT_REPOSITORY_URL,
    branch: str = DEFAULT_BRANCH,
) -> List[WebProblem]:
    source_list = list(sources)
    claim_list = list(claims)
    sources_by_id = {source.source_id: source for source in source_list}
    problems: List[WebProblem] = [
        _claim_problem(claim, sources_by_id, repository_url, branch)
        for claim in claim_list
    ]
    qa_count = 0
    for source in source_list:
        cards = source.metadata.get("engineering_qa", [])
        if not isinstance(cards, list):
            continue
        qa_count += len(cards)
        for card in cards:
            if not isinstance(card, Mapping):
                raise WebSearchError(
                    f"{source.source_id} engineering_qa items must be objects"
                )
            problems.append(_qa_problem(source, card, repository_url, branch))
    expected_count = len(claim_list) + qa_count
    if len(problems) != expected_count:
        raise WebSearchError(
            f"web problem count mismatch: expected {expected_count}, got {len(problems)}"
        )
    problems.sort(key=lambda problem: problem.problem_id)
    seen = set()
    for problem in problems:
        if problem.problem_id in seen:
            raise WebSearchError(f"duplicate web problem id: {problem.problem_id}")
        seen.add(problem.problem_id)
    return problems


def render_problem_pages(
    problems: Iterable[WebProblem], output_dir: Path, check: bool = False
) -> Dict[str, int]:
    problem_list = list(problems)
    output_dir = Path(output_dir)
    expected = {Path(problem.relative_path).name: problem.markdown for problem in problem_list}
    existing = {
        path.name: path
        for path in output_dir.glob("*.md")
        if path.is_file()
    } if output_dir.exists() else {}

    mismatches = []
    for name, content in expected.items():
        path = output_dir / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            mismatches.append(name)
    extras = sorted(set(existing) - set(expected))
    if check:
        if mismatches or extras:
            parts = []
            if mismatches:
                parts.append(f"missing_or_stale={len(mismatches)}")
            if extras:
                parts.append(f"extra={len(extras)}")
            raise WebSearchError("problem pages are not current: " + ", ".join(parts))
        return {"problems": len(problem_list), "written": 0, "removed": 0}

    output_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    for name, content in expected.items():
        path = output_dir / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            written += 1
    removed = 0
    for name in extras:
        path = existing[name]
        text = path.read_text(encoding="utf-8")
        if not text.startswith(GENERATED_MARKER):
            raise WebSearchError(f"refusing to remove non-generated page: {path}")
        path.unlink()
        removed += 1
    return {"problems": len(problem_list), "written": written, "removed": removed}


def build_web_index(
    problems: Iterable[WebProblem], problems_dir: Path, output_path: Path
) -> Dict[str, int]:
    problem_list = list(problems)
    problems_dir = Path(problems_dir)
    for problem in problem_list:
        path = problems_dir / Path(problem.relative_path).name
        if not path.is_file():
            raise WebSearchError(f"missing problem page: {path}")
    items = [problem.search_item() for problem in problem_list]
    for item in items:
        forbidden = FORBIDDEN_SEARCH_FIELDS.intersection(item)
        if forbidden:
            raise WebSearchError(
                "search item leaks credibility fields: " + ", ".join(sorted(forbidden))
            )
    payload = {"schema_version": 1, "items": items}
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return {"problems": len(problem_list), "items": len(items)}
